//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intersoft_ProjectOnline_QC_2017.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IMSDEV2014SQL;Initial Catalog=PSO_Intersoft;User Id=sqltimesaldobruke" +
            "r;Password=Intersoft2016")]
        public string PROD_DBConnection {
            get {
                return ((string)(this["PROD_DBConnection"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source =imssqlreporting; Initial Catalog = PSO_Intersoft; Integrated Securit" +
            "y = True")]
        public string DEV_DBConnection {
            get {
                return ((string)(this["DEV_DBConnection"]));
            }
            set {
                this["DEV_DBConnection"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TEST_DBConnection {
            get {
                return ((string)(this["TEST_DBConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string UseTimesaldo {
            get {
                return ((string)(this["UseTimesaldo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PTR_AppName {
            get {
                return ((string)(this["PTR_AppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PTR_AppEvent {
            get {
                return ((string)(this["PTR_AppEvent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PRR_AppName {
            get {
                return ((string)(this["PRR_AppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PRR_AppEvent {
            get {
                return ((string)(this["PRR_AppEvent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Count Rows short - Intersoft.xlsx")]
        public string DEV_QC_Reportname {
            get {
                return ((string)(this["DEV_QC_Reportname"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Count Rows short - Intersoft.xlsx")]
        public string TEST_QC_Reportname {
            get {
                return ((string)(this["TEST_QC_Reportname"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PROD_PO_Username {
            get {
                return ((string)(this["PROD_PO_Username"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PROD_PO_Password {
            get {
                return ((string)(this["PROD_PO_Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PROD_PO_URL_PWA {
            get {
                return ((string)(this["PROD_PO_URL_PWA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TEST_PO_Username {
            get {
                return ((string)(this["TEST_PO_Username"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TEST_PO_Password {
            get {
                return ((string)(this["TEST_PO_Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TEST_PO_PWA_URL {
            get {
                return ((string)(this["TEST_PO_PWA_URL"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DEV_PO_Username {
            get {
                return ((string)(this["DEV_PO_Username"]));
            }
            set {
                this["DEV_PO_Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DEV_PO_Password {
            get {
                return ((string)(this["DEV_PO_Password"]));
            }
            set {
                this["DEV_PO_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DEV_PO_PWA_URL {
            get {
                return ((string)(this["DEV_PO_PWA_URL"]));
            }
            set {
                this["DEV_PO_PWA_URL"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string POD_AppName {
            get {
                return ((string)(this["POD_AppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string POD_AppEvent {
            get {
                return ((string)(this["POD_AppEvent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\richard.lie\\Desktop\\")]
        public string PROD_QC_ReportPath {
            get {
                return ((string)(this["PROD_QC_ReportPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public string Enviroment {
            get {
                return ((string)(this["Enviroment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TEST_QC_ReportPath {
            get {
                return ((string)(this["TEST_QC_ReportPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DEV_QC_ReportPath {
            get {
                return ((string)(this["DEV_QC_ReportPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POQualityCheck2017.xlsx")]
        public string PROD_QC_Reportname {
            get {
                return ((string)(this["PROD_QC_Reportname"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string UseReportRefresh {
            get {
                return ((string)(this["UseReportRefresh"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intersoft Production")]
        public string QC_SITE_1 {
            get {
                return ((string)(this["QC_SITE_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string QC_SITE_SEQ_1 {
            get {
                return ((string)(this["QC_SITE_SEQ_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string QC_SITE_SEQ_2 {
            get {
                return ((string)(this["QC_SITE_SEQ_2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intersoft Test 2")]
        public string QC_SITE_3 {
            get {
                return ((string)(this["QC_SITE_3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IMSDEV2014SQL;Initial Catalog=PSO_Intersoft;User Id=sqltimesaldobruke" +
            "r;Password=Intersoft2016")]
        public string QC_SITE_DBC_3 {
            get {
                return ((string)(this["QC_SITE_DBC_3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string QC_SITE_SEQ_3 {
            get {
                return ((string)(this["QC_SITE_SEQ_3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intersoft Test 4")]
        public string QC_SITE_4 {
            get {
                return ((string)(this["QC_SITE_4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IMSDEV2014SQL;Initial Catalog=PSO_Intersoft;User Id=sqltimesaldobruke" +
            "r;Password=Intersoft2016")]
        public string QC_SITE_DBC_4 {
            get {
                return ((string)(this["QC_SITE_DBC_4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string QC_SITE_SEQ_4 {
            get {
                return ((string)(this["QC_SITE_SEQ_4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intersoft Test 5")]
        public string QC_SITE_5 {
            get {
                return ((string)(this["QC_SITE_5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IMSDEV2014SQL;Initial Catalog=PSO_Intersoft;User Id=sqltimesaldobruke" +
            "r;Password=Intersoft2016")]
        public string QC_SITE_DBC_5 {
            get {
                return ((string)(this["QC_SITE_DBC_5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string QC_SITE_SEQ_5 {
            get {
                return ((string)(this["QC_SITE_SEQ_5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string QC_TEST_TYPE {
            get {
                return ((string)(this["QC_TEST_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string QC_NUMBERS_OF_SITE {
            get {
                return ((string)(this["QC_NUMBERS_OF_SITE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IMSSQLREPORTING;Initial Catalog=PSO_Intersoft_History;Integrated Secu" +
            "rity=SSPI")]
        public string QC_SITE_DBC_1 {
            get {
                return ((string)(this["QC_SITE_DBC_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intersoft Demo ")]
        public string QC_SITE_2 {
            get {
                return ((string)(this["QC_SITE_2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IMSSQLREPORTING;Initial Catalog=PSO_Intersoft_History_Demo;Integrated" +
            " Security=SSPI")]
        public string QC_SITE_DBC_2 {
            get {
                return ((string)(this["QC_SITE_DBC_2"]));
            }
        }
    }
}
